import {MyAccount} from "./MyAcount.js"
import {SettingScreen} from "./SettingScreen.js"
import {NotificationScreen} from "./NotificationScreen.js"
import {Privacy} from "./Privacy.js"
import {ChangePassword} from "./ChangePassword.js"
import {HelpandSupport} from "./HelpandSupport.js"
import {FAQ} from "./FAQ.js"
import {EditProfile} from "./EditProfile"
import {Friends} from "./Friends"
import {VfastProducts} from "./VfastProducts"
import {QRDetails} from "./QRDetails"
import {TermsConditions} from "./TermsConditions"
import {PrivacyPolicy} from "./PrivacyPolicy"
module.exports={MyAccount,SettingScreen,NotificationScreen,Privacy,HelpandSupport,ChangePassword,FAQ,EditProfile,Friends,VfastProducts,QRDetails,TermsConditions,PrivacyPolicy}